# -*- coding: utf-8 -*-
"""volume_of_sphere

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNIUqdrB3Y-Y7m5o6VK7_8JBqsfIe6br
"""

import math

def calculate_volume_of_sphere(radius):
  volume = (4/3) * math.pi * (radius ** 3)
  return volume

volume_30 = calculate_volume_of_sphere(30)
volume_40 = calculate_volume_of_sphere(40)

print("Volume of a sphere with a radius of 30:", volume_30)
print("Volume of a sphere with a radius of 40:", volume_40)